import { execFileSync } from "node:child_process";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { afterEach, describe, expect, it } from "vitest";

const projectRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../../..");
const tempRoots = [];

describe("generate-event-content-manifest", () => {
  afterEach(() => {
    while (tempRoots.length > 0) {
      fs.rmSync(tempRoots.pop(), { recursive: true, force: true });
    }
  });

  it("generates static imports for every manifest event domain", () => {
    const root = createContentRoot();
    const outputPath = path.join(root, "apps/pc-client/src/content/generated/eventContentManifest.ts");
    writeJson(root, "content/events/manifest.json", {
      schema_version: "event-manifest.v1",
      domains: [
        manifestDomain("crash_site"),
        manifestDomain("desert"),
        manifestDomain("forest", "presets/forest.json"),
        manifestDomain("mainline_crash_site"),
        manifestDomain("mainline_ending"),
        manifestDomain("mainline_hive"),
        manifestDomain("mainline_medical"),
        manifestDomain("mainline_resources"),
        manifestDomain("mainline_village"),
        manifestDomain("mine"),
        manifestDomain("mountain"),
      ],
    });

    execFileSync(
      "node",
      [
        path.join(projectRoot, "apps/editor/scripts/generate-event-content-manifest.mjs"),
        "--root",
        root,
        "--out",
        outputPath,
      ],
      { cwd: projectRoot },
    );

    const generated = fs.readFileSync(outputPath, "utf8");
    expect(generated).toContain("This file is auto-generated by apps/editor/scripts/generate-event-content-manifest.mjs");
    expect(generated).toContain(
      'import crashSiteEventDefinitionsContent from "../../../../../content/events/definitions/crash_site.json";',
    );
    expect(generated).not.toContain("crewKael");
    expect(generated).not.toContain("crew_kael");
    expect(generated).toContain(
      'import forestPresetsContent from "../../../../../content/events/presets/forest.json";',
    );
    expect(generated).toContain(
      'import mainlineCrashSiteEventDefinitionsContent from "../../../../../content/events/definitions/mainline_crash_site.json";',
    );
    expect(generated).toContain("export const generatedEventDomains = [");
    expect(generated).toContain('  "crash_site",');
    expect(generated).toContain('  "mainline_crash_site",');
    expect(generated).toContain('  "mountain",');
    expect(generated).toContain("export const generatedEventProgramDefinitions");
    expect(generated).toContain("...mountainCallTemplatesContent.call_templates");
  });
});

function createContentRoot() {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), "stellar-event-manifest-"));
  tempRoots.push(root);
  fs.cpSync(path.join(projectRoot, "content"), path.join(root, "content"), { recursive: true });
  return root;
}

function writeJson(root, relativePath, value) {
  fs.mkdirSync(path.dirname(path.join(root, relativePath)), { recursive: true });
  fs.writeFileSync(path.join(root, relativePath), `${JSON.stringify(value, null, 2)}\n`);
}

function manifestDomain(id, presets = null) {
  return {
    id,
    definitions: `definitions/${id}.json`,
    call_templates: `call_templates/${id}.json`,
    presets,
  };
}
