import { execFileSync } from "node:child_process";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { afterEach, describe, expect, it } from "vitest";

const projectRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../../..");
const tempRoots = [];

describe("generate-event-content-manifest", () => {
  afterEach(() => {
    while (tempRoots.length > 0) {
      fs.rmSync(tempRoots.pop(), { recursive: true, force: true });
    }
  });

  it("generates static imports for every manifest event domain", () => {
    const root = createContentRoot();
    const outputPath = path.join(root, "apps/pc-client/src/content/generated/eventContentManifest.ts");

    execFileSync(
      "node",
      [
        path.join(projectRoot, "apps/editor/scripts/generate-event-content-manifest.mjs"),
        "--root",
        root,
        "--out",
        outputPath,
      ],
      { cwd: projectRoot },
    );

    const generated = fs.readFileSync(outputPath, "utf8");
    expect(generated).toContain("This file is auto-generated by apps/editor/scripts/generate-event-content-manifest.mjs");
    expect(generated).toContain(
      'import iafsInspectionEventDefinitionsContent from "../../../../../content/events/definitions/iafs-inspection.json";',
    );
    expect(generated).not.toContain(["crew", "Kael"].join(""));
    expect(generated).not.toContain(["crew", "_", "ka", "el"].join(""));
    expect(generated).toContain(
      'import iafsInspectionCallTemplatesContent from "../../../../../content/events/call_templates/iafs-inspection.json";',
    );
    expect(generated).toContain("export const generatedEventDomains = [");
    expect(generated).toContain('  "iafs-inspection",');
    expect(generated).toContain("export const generatedEventProgramDefinitions");
    expect(generated).toContain("...iafsInspectionCallTemplatesContent.call_templates");
  });
});

function createContentRoot() {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), "stellar-event-manifest-"));
  tempRoots.push(root);
  fs.cpSync(path.join(projectRoot, "content"), path.join(root, "content"), { recursive: true });
  return root;
}
